In [40]:
import pandas as pd
import numpy as np

df = pd.read_csv("ecommerce_customer_behavior_dataset_v2.csv")

df.head()

       Order_ID Customer_ID  ... Delivery_Time_Days  Customer_Rating
0  ORD_000001-1  CUST_00001  ...                 13                4
1  ORD_000001-2  CUST_00001  ...                  6                2
2  ORD_000001-3  CUST_00001  ...                  9                4
3  ORD_000002-1  CUST_00002  ...                  4                4
4  ORD_000002-2  CUST_00002  ...                  6                4

[5 rows x 18 columns]

In [41]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 17049 entries, 0 to 17048
Data columns (total 18 columns):
 #   Column                    Non-Null Count  Dtype
---  ------                    --------------  -----
 0   Order_ID                  17049 non-null  object
 1   Customer_ID               17049 non-null  object
 2   Date                      17049 non-null  object
 3   Age                       17049 non-null  int64
 4   Gender                    17049 non-null  object
 5   City                      17049 non-null  object
 6   Product_Category          17049 non-null  object
 7   Unit_Price                17049 non-null  float64
 8   Quantity                  17049 non-null  int64
 9   Discount_Amount           17049 non-null  float64
 10  Total_Amount              17049 non-null  float64
 11  Payment_Method            17049 non-null  object
 12  Device_Type               17049 non-null  object
 13  Session_Duration_Minutes  17049 non-null  int64
 14  Pages_Viewed              17049 non-null  int64
 15  Is_Returning_Customer     17049 non-null  bool
 16  Delivery_Time_Days        17049 non-null  int64
 17  Customer_Rating           17049 non-null  int64
dtypes: bool(1), float64(3), int64(6), object(8)
memory usage: 2.2+ MB

In [42]:
df.describe()

                Age    Unit_Price  ...  Delivery_Time_Days  Customer_Rating
count  17049.000000  17049.000000  ...        17049.000000     17049.000000
mean      34.945745    447.901689  ...            6.503607         3.899408
std       11.046855    722.319705  ...            3.488787         1.128803
min       18.000000      5.050000  ...            1.000000         1.000000
25%       26.000000     73.260000  ...            4.000000         3.000000
50%       35.000000    174.680000  ...            6.000000         4.000000
75%       42.000000    494.570000  ...            8.000000         5.000000
max       75.000000   7900.010000  ...           25.000000         5.000000

[8 rows x 9 columns]

In [43]:
df.isnull().sum()

Order_ID                    0
Customer_ID                 0
Date                        0
Age                         0
Gender                      0
City                        0
Product_Category            0
Unit_Price                  0
Quantity                    0
Discount_Amount             0
Total_Amount                0
Payment_Method              0
Device_Type                 0
Session_Duration_Minutes    0
Pages_Viewed                0
Is_Returning_Customer       0
Delivery_Time_Days          0
Customer_Rating             0
dtype: int64

In [44]:
df = df.dropna()

In [45]:
df.duplicated().sum()

np.int64(0)

In [47]:
df['Date'] = pd.to_datetime(df['Date'])

In [48]:
df['Month'] = df['Date'].dt.month
df['Year'] = df['Date'].dt.year

In [49]:
df[df['Quantity'] <= 0]

Empty DataFrame
Columns: [Order_ID, Customer_ID, Date, Age, Gender, City, Product_Category, Unit_Price, Quantity, Discount_Amount, Total_Amount, Payment_Method, Device_Type, Session_Duration_Minutes, Pages_Viewed, Is_Returning_Customer, Delivery_Time_Days, Customer_Rating, Month, Year]
Index: []

In [50]:
df['Calculated_Total'] = df['Unit_Price'] * df['Quantity'] - df['Discount_Amount']

In [56]:
df.drop(columns="Calculated_Total", inplace=True)

In [57]:
df['Product_Category'] = df['Product_Category'].str.strip()
df['Gender'] = df['Gender'].str.title()

In [58]:
df['Discount_Percentage'] = round((df['Discount_Amount'] / (df['Unit_Price'] * df['Quantity'])) * 100,2)

In [59]:
bins = [18,25,35,45,55,65,80]
labels = ['18-24','25-34','35-44','45-54','55-64','65+']

df['Age_Group'] = pd.cut(df['Age'], bins=bins, labels=labels)

In [60]:
df

           Order_ID Customer_ID       Date  ...  Year Discount_Percentage Age_Group
0      ORD_000001-1  CUST_00001 2023-05-29  ...  2023                0.00     35-44
1      ORD_000001-2  CUST_00001 2023-10-12  ...  2023               21.42     35-44
2      ORD_000001-3  CUST_00001 2023-12-05  ...  2023                0.00     35-44
3      ORD_000002-1  CUST_00002 2023-05-11  ...  2023               20.51     25-34
4      ORD_000002-2  CUST_00002 2023-06-16  ...  2023                0.00     25-34
...             ...         ...        ...  ...   ...                 ...       ...
17044  ORD_004999-1  CUST_04999 2024-01-16  ...  2024                0.00     35-44
17045  ORD_005000-1  CUST_05000 2023-02-22  ...  2023                0.00     18-24
17046  ORD_005000-2  CUST_05000 2023-06-29  ...  2023                0.00     18-24
17047  ORD_005000-3  CUST_05000 2023-12-29  ...  2023                9.22     18-24
17048  ORD_005000-4  CUST_05000 2024-01-19  ...  2024                5.34     18-24

[17049 rows x 22 columns]

In [61]:
df.to_csv("Clean_E-Commerce_Data.csv", index=False)